### PR TITLE
Refactor some process handling 

### PR DESCRIPTION
**Pull request by mrtank**
PriorityProcessorTests created to increase code coverage.

Fix some _<field> naming errors.

Join, Learn, Help, Leave commands moves to NativeCommands (BaseCommand descendants)

BaseCommands now built by factory.
This enables NativeCommands to use the DI framework magic with same setup as the MVC app.

Eliminate some unnecessary dependencies.
While at it, it became clear, that `ProcessCommand` is only processing native commands, and `ProcessCommandAsync` is only processing dynamic commands. Made it clear by changing the names.

### CODE REVIEW

**Comment by butler1233** [comment]
I finally merged the other commit, Update th is one and then it's good to go

**Comment by mrtank** [comment]
> I finally merged the other commit, Update th is one and then it's good to go

I'll wait for the fix, than update.

**Comment by butler1233** [comment]
Done, I wasn't even paying attention lol

**Comment by mrtank** [comment]
merging done

**Pull request merged**
