### PR TITLE
Clean up commands

### PR DESCRIPTION
**Pull request by Regenhardt**

### CODE REVIEW

**Review by butler1233 — APPROVED** [review]
I mena it looks like it probably works but I'm tired so I can't be arsed reading it properly. I guess we'll find out when it merges in and see what happens.

**Comment by butler1233** [comment]
It's entirely possible that I sorta mangled this one with my changes on master. Can you give it a quick check?

**Comment by Regenhardt** [comment]
Can confirm mangled-ness. Tried to fix it. Just gotta find out how to fix a conflict in github now.

**Comment by Regenhardt** [comment]
Did it. Not sure how but I did it.

**Comment by butler1233** [comment]
If it builds in the pipeline I'll merge it and we can see how it goes. Come online and have a play if you like

**Pull request merged**
