### PR TITLE
Crossplatform pings and inline code

### PR DESCRIPTION
**Pull request by hrkrx**
fixes inline code from chat.so -> discord

pinging a user on chat.so, entails that the bot now tries to resolve the name to a user on discord and pings them there too.
this also works for roles. 

since the regex depends on spaces as seperator it does not work correctly for weird names.

### CODE REVIEW

**Comment by hrkrx** [comment]
For the pings to work, the bot needs the Server Member Intent
image

**Comment by butler1233** [comment]
Enabled. Give it a go and see if it works

**Comment by hrkrx** [comment]
Accidentally closed it in the mobile app ^^"

**Comment by hrkrx** [comment]
Is there anything missing for you to merge this?

**Comment by butler1233** [comment]
No I just hadn't looked yet. Although now you've got the TTS PR which appears to be forked from this one I'm closing it and we can follow on the TTS one.

**Pull request closed without merging**
